name: Daily scrape

on:
  schedule:
    - cron: '0 23 * * *'   # every day at 23:00 UTC (~9 AM Brisbane)
  workflow_dispatch:      # enables manual “Run workflow” button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape.py

      - name: List workspace files
        run: ls -lah

      - name: Commit CSV (if changed)
        continue-on-error: true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add punters_meeting.csv
          if [[ -n "$(git diff --cached --name-only)" ]]; then
            git commit -m "Daily scrape $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to punters_meeting.csv — skipping commit."
          fi


